TOKEN = '5732920823:AAEBS3K7iJIHp8IR5c5r1xFkGs0xV1893Iw'
VACANCY_GROUP_ID = "your-vacancy-group-id"
SERVICE_GROUP_ID = "your-vacancy-service-id"

VACANCY_HASHTAGS = ['company_name', 'job_title', 'type_of_work']
SERVICE_HASHTAGS = ['job_title', 'type_of_work']

REQUIREMENT_CHARACTERS = 300
TERM_CHARACTERS = 300
SERVICE_CHARACTERS = 300
COMPANY_NAME_CHARACTERS = 20
JOB_TITLE_CHARACTERS = 20
SALARY_CHARACTERS = 10
CONTACT_CHARACTERS = 12
PORTFOLIO_CHARACTERS = 40
